name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  # On master/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build-test:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest, windows-latest ]
    name: 'Test, ${{ matrix.os }}, java ${{ matrix.java }}'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - name: Test
        run: |
          ./mvnw --color=always -B verify
      - uses: actions/upload-artifact@v3
        name: Attach generated update site as zip
        if: matrix.os == 'ubuntu-latest'
        with:
          name: mat-calcite-plugin-update-site
          # actions/upload-artifact always creates .zip, so we specify directory here to prevent double zip archiving
          path: MatCalciteRepository/target/repository/*
          # Default retention is 90 days, and we publish the archives to the update site anyway
          retention-days: 4
      - name: Publish Eclipse update site
        if: matrix.os == 'ubuntu-latest' && github.repository == 'vlsi/mat-calcite-plugin' && github.ref == 'refs/heads/main'
        uses: ./.github/actions/publish-update-site
        with:
          update_site_token:
            ${{ secrets.UPDATE_SITE_TOKEN }}
